apiVersion: v1
kind: Pod
metadata:
  name: pod-dbm
spec:
  containers:
    - name: oracle-db
      # image: container-registry.oracle.com/database/enterprise:21.3.0.0
      image: container-registry.oracle.com/database/enterprise:19.3.0.0
      ports:
        - containerPort: 1521
          hostPort: 1521
          protocol: TCP
      env:
        - name: ORACLE_PWD
          value: system
      volumeMounts:
        - name: oracle-db-oradata
          mountPath: /opt/oracle/oradata
      securityContext:
        runAsUser: 54321 # Oracle's default user for the database, adjust if your image is different
        runAsGroup: 54321
        fsGroup: 54321
        fsGroupChangePolicy: "OnRootMismatch"

    - name: mssql-db
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
          hostPort: 1433
          protocol: TCP
      env:
        - name: ACCEPT_EULA
          value: Y
        - name: MSSQL_SA_PASSWORD
          value: system!SA3
      volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data



  volumes:
    # Volume for 'oracle-db' container
    - name: oracle-db-oradata
      persistentVolumeClaim:
        claimName: oracle-db-oradata
      ## This is to use physical file in the system
      # hostPath:
        #   path: /home/viaguila/containers/other/oracle-db/data/oradata:Z
      #   type: DirectoryOrCreate
    # Volume for 'mssql-db' container
    - name: mssql-data
      persistentVolumeClaim:
        claimName: mssql-data
      ## This is to use physical file in the system
      # hostPath:
        #   path: /home/viaguila/containers/other/mssql-db/data:Z
      #   type: DirectoryOrCreate

